{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goodfood.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "traefik" }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range $key, $svc := .Values.services }}
          {{- if and $svc.enabled $svc.path }}
          - path: {{ $svc.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $svc.name }}
                port:
                  number: {{ $svc.port | default 8080 }}
          {{- end }}
          {{- end }}
{{- end }}
