{{- range $key, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
spec:
  type: {{ ($svc.service).type | default "ClusterIP" }}
  selector:
    app: {{ $svc.name }}
  ports:
    - name: http
      port: {{ $svc.port | default 8080 }}
      targetPort: {{ $svc.port | default 8080 }}
      {{- if and (eq (($svc.service).type | default "ClusterIP") "NodePort") ($svc.service).nodePort }}
      nodePort: {{ ($svc.service).nodePort }}
      {{- end }}
---
{{- end }}
{{- end }}
